ALTER TABLE khoa ADD
CONSTRAINT pk_khoa PRIMARY KEY MaKhoa;

ALTER TABLE giangvien ADD
CONSTRAINT pk_gv PRIMARY KEY MaGV;

ALTER TABLE giangvien ADD
CONSTRAINT fk_GV_K FOREIGN KEY MaKhoa REFERENCES khoa;
